apiVersion: v1
kind: Secret
metadata:
  name: billing-secrets
  namespace: mechanics-billing
  labels:
    app: mechanics-billing
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "Host=${DB_HOST};Port=5432;Database=billing;Username=${DB_USER};Password=${DB_PASSWORD}"
  ConnectionStrings__Mongo: "${MONGO_CONNECTION_STRING}"
  MERCADOPAGO_ACCESS_TOKEN: "${MERCADOPAGO_ACCESS_TOKEN}"
  MERCADOPAGO_WEBHOOK_SECRET: "${MERCADOPAGO_WEBHOOK_SECRET}"
  RABBITMQ_CONNECTION_STRING: "${RABBITMQ_CONNECTION_STRING}"
